[package]
name = "primus"
version = "0.1.0"
edition = "2021"
description = "Transform data" 
license = "GPL-3.0-only"
repository = "https://github.com/loicbourgois/primus"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
